version: '3.8'

name: discord-bot-tickers
services:
  redis:
    image: redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    network_mode: "host"
    volumes:
      - ./redis/logs:/app/logs
    restart: always

  server:
    image: server
    build: 
      context: .
      dockerfile: dockerfile.server
    depends_on:
      - redis
    network_mode: "host"
    volumes:
      - ./server/logs:/app/logs
    restart: always

  tickers:
    image: tickers
    build:
      context: .
      dockerfile: dockerfile.tickers
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - server
    network_mode: "host"
    volumes:
      - ./tickers/logs:/app/logs
    restart: always

  market-wiz:
    image: market-wiz
    build:
      context: .
      dockerfile: dockerfile.marketwiz
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    volumes:
      - ./market-wiz/logs:/app/logs
    restart: always
    platform: linux/amd64



networks:
  app-network:
      driver: bridge
