FROM python:3.10-slim

WORKDIR /app

COPY  .env /app/.env
COPY ./server .
RUN pip install --no-cache-dir -r .requirements.txt

EXPOSE 8000

# CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:8000", "app:app"]
CMD ["python", "app.py"]



