version: '3.8'

name: discord-bot-tickers
services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      app-network:
        ipv4_address: 172.30.0.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    image: server
    build: 
      context: .
      dockerfile: dockerfile.server
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./server/logs:/app/logs
    restart: always
    networks:
      app-network:
        ipv4_address: 172.30.0.3

  tickers:
    image: tickers
    build:
      context: .
      dockerfile: dockerfile.tickers
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
      server:
        condition: service_started
    volumes:
      - ./tickers/logs:/app/logs
    restart: always
    networks:
      app-network:
        ipv4_address: 172.30.0.4

  market-wiz:
    image: market-wiz
    build:
      context: .
      dockerfile: dockerfile.marketwiz
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    volumes:
      - ./market-wiz/logs:/app/logs
    restart: always
    platform: linux/amd64
    depends_on:
      redis:
        condition: service_healthy
    networks:
      app-network:
        ipv4_address: 172.30.0.5

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: always
    networks:
      app-network:
        ipv4_address: 172.30.0.6

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1


