version: '3.8'

name: discord-bot-tickers
services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network

  server:
    image: server
    build: 
      context: .
      dockerfile: dockerfile.server
    depends_on:
      - redis
    volumes:
      - ./server/logs:/app/logs
    restart: always
    networks:
      app-network:
        ipv4_address: 172.20.0.3

  tickers:
    image: tickers
    build:
      context: .
      dockerfile: dockerfile.tickers
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - server
    volumes:
      - ./tickers/logs:/app/logs
    restart: always
    networks:
      - app-network

  market-wiz:
    image: market-wiz
    build:
      context: .
      dockerfile: dockerfile.marketwiz
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    volumes:
      - ./market-wiz/logs:/app/logs
    restart: always
    platform: linux/amd64
    depends_on:
      - redis
    networks:
      - app-network

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1


